# Generated by Django 5.2.5 on 2025-11-12 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, help_text='Set when status becomes active for the first time', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by student for this enrollment. Cannot exceed the class price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount Paid')),
                ('payment_ref', models.CharField(blank=True, max_length=255, verbose_name='Payment Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.class')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ('-created_at',),
                'unique_together': {('student', 'class_enrolled')},
            },
        ),
    ]
