# Generated by Django 5.0.1 on 2025-11-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentparentprofile',
            options={'verbose_name': 'Student Parent Relationship', 'verbose_name_plural': 'Student Parent Relationships'},
        ),
        migrations.AlterField(
            model_name='studentparentprofile',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
