# Generated by Django 5.2.5 on 2025-11-12 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ManyToManyField(related_name='company_settings', to='core.companycontact')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_type', models.CharField(choices=[('custom_request', 'Custom Course Request'), ('contact_message', 'Contact Message'), ('report', 'Report')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('new', 'New'), ('read', 'Read'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('family', 'Family Course'), ('private', 'Private Class (1-on-1)'), ('group', 'Small Group (2-5 people)'), ('corporate', 'Corporate Training')], max_length=20, null=True)),
                ('number_of_students', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_schedule', models.CharField(blank=True, choices=[('morning', 'Morning (8am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-9pm)'), ('weekend', 'Weekend Only'), ('flexible', 'Flexible')], max_length=20, null=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('bug', 'Bug/Issue'), ('content', 'Inappropriate Content'), ('feedback', 'Feedback'), ('suggestion', 'Suggestion'), ('other', 'Other')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='reports/screen_shots/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Communication',
                'verbose_name_plural': 'User Communications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['communication_type', 'status'], name='core_userco_communi_bb5d97_idx'), models.Index(fields=['created_at'], name='core_userco_created_e7f6d7_idx'), models.Index(fields=['user'], name='core_userco_user_id_111338_idx')],
            },
        ),
    ]
