# Generated by Django 5.2.5 on 2025-11-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('courseType', models.CharField(choices=[('family', 'Family Course'), ('private', 'Private Class (1-on-1)'), ('group', 'Small Group (2-5 people)'), ('corporate', 'Corporate Training')], max_length=20)),
                ('numberOfStudents', models.CharField(blank=True, max_length=10, null=True)),
                ('preferredSchedule', models.CharField(blank=True, choices=[('morning', 'Morning (8am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-9pm)'), ('weekend', 'Weekend Only'), ('flexible', 'Flexible')], max_length=20, null=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_course_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Course Request',
                'verbose_name_plural': 'Custom Course Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
