# Generated by Django 5.2.5 on 2025-11-12 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollments.classenrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='classes', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='class_completed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='course.class'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='course.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='course.livesession'),
        ),
        migrations.AddField(
            model_name='livesessionresource',
            name='session',
            field=models.ForeignKey(help_text='The live session this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='course.livesession'),
        ),
        migrations.AddField(
            model_name='livesessionresource',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this resource', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recording',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='course.livesession'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('class_enrollment', 'session'), name='unique_attendance_per_session'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_enrollment', 'session')},
        ),
        migrations.AddIndex(
            model_name='livesessionresource',
            index=models.Index(fields=['session', '-created_at'], name='course_live_session_8c5951_idx'),
        ),
    ]
