# Generated by Django 5.2.5 on 2025-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='is_recording',
            field=models.BooleanField(default=False, help_text='Whether recording is currently active'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_file',
            field=models.FileField(blank=True, help_text='The recording file', null=True, upload_to='recordings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, help_text='When recording started', null=True),
        ),
    ]
