# Generated by Django 5.2.5 on 2025-11-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_email_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='email_verif_token_df7c5e_idx',
            old_name='email_veri_token_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='email_verif_user_id_867e40_idx',
            old_name='email_veri_user_id_def456_idx',
        ),
    ]
