# Generated by Django 5.0.1 on 2025-12-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_veri_token_abc123_idx_email_verif_token_df7c5e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('attempt_count', models.IntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_verification_attempts',
                'indexes': [models.Index(fields=['email'], name='email_verif_email_885ee0_idx'), models.Index(fields=['locked_until'], name='email_verif_locked__675551_idx')],
            },
        ),
    ]
