# Generated by Django 5.2.5 on 2025-11-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_transliteration', models.CharField(max_length=100)),
                ('name_translation', models.CharField(max_length=200)),
                ('total_verses', models.IntegerField()),
                ('revelation_type', models.CharField(choices=[('meccan', 'Meccan'), ('medinan', 'Medinan')], max_length=10)),
            ],
            options={
                'verbose_name': 'Surah',
                'verbose_name_plural': 'Surahs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('text_arabic', models.TextField()),
                ('text_translation', models.TextField()),
                ('text_transliteration', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
                'ordering': ['surah__number', 'verse_number'],
                'unique_together': {('surah', 'verse_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_verse', models.IntegerField(default=1)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_history', to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah')),
            ],
            options={
                'verbose_name': 'Reading History',
                'verbose_name_plural': 'Reading Histories',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'surah')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.verse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'verse')},
            },
        ),
    ]
