# Generated by Django 5.2.5 on 2025-11-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='The chat message content')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System')], default='text', help_text='Type of message', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('read_by', models.ManyToManyField(blank=True, help_text='Users who have read this message', related_name='read_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The live session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='course.livesession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chats_chatm_session_320c1e_idx')],
            },
        ),
    ]
